export const USER_COOKIE = 'cmx_UID';

export const discountTypes = {
  DISCOUNT: 'discount',
  PROMOTION: 'promotion',
  LOYALTY_STATUS: 'loyaltyStatus',
  GROUP_DISCOUNT: 'groupDiscount'
};

export const amountTypes = {
  PERCENT: 'PERCENT',
  EXACT: 'EXACT',
  AMOUNT: 'AMOUNT'
};

export const paymentProcessors = { 
   
  UNDEFINED:'UNDEFINED', 
  STRIPE:'STRIPE', 
  PAYPAL:'PAYPAL',

  VANTIV_CHIP:'VANTIV_CHIP',
  VANTIV_HID: 'VANTIV_HID',
  VANTIV_ECOMMERCE:'VANTIV_ECOMMERCE',

  TSYS_CHIP:'TSYS_CHIP',
  TSYS_HID:'TSYS_HID',
  TSYS_ECOMMERCE:'TSYS_ECOMMERCE', 

  HEARTLAND_CHIP:'HEARTLAND_CHIP',
  HEARTLAND_HID:'HEARTLAND_HID',
  HEARTLAND_ECOMMERCE:'HEARTLAND_ECOMMERCE',

  SHIFT4_CHIP:'SHIFT4_CHIP',
  SHIFT4_HID:'SHIFT4_HID', 
  SHIFT4_ECOMMERCE:'SHIFT4_ECOMMERCE',

  NABANCARD_CHIP:'NABANCARD_CHIP',
  NABANCARD_HID:'NABANCARD_HID',
  NABANCARD_ECOMMERCE:'NABANCARD_ECOMMERCE',

  CARDCONNECT_CHIP:'CARDCONNECT_CHIP',
  CARDCONNECT_HID:'CARDCONNECT_HID',
  CARDCONNECT_ECOMMERCE:'CARDCONNECT_ECOMMERCE'

};

export const serviceStatuses = {
  CALL_AHEAD: 'CALL_AHEAD',
  CLOSED: 'CLOSED'
};

export const userSASLSummaryPriorities = {
  NONE: 'NONE',
  NOTIFICATION: 'NOTIFICATION',
  HIGHLIGHTED_ITEM: 'HIGHLIGHTED_ITEM',
  POLL: 'POLL'
};

export const googleMapAPIKey = 'AIzaSyDon847P6x8IUl-pBwSMvvuZd3g2186uhQ';
